name: swap-correction
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  # Development dependencies
  - pytest>=7.0
  - pytest-cov>=4.0
  - black>=23.0
  - flake8>=6.0
  - mypy>=1.0
  - mkdocs>=1.0
  - mkdocs-material>=9.0
  - isort>=5.0.0
  - pip:
      - -e . 